
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        include:
          - name: '1'
          - name: '2'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo GITHUB_RUN_ID $GITHUB_RUN_ID vs. GITHUB_RUN_NUMBER $GITHUB_RUN_NUMBER

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
